Repository CustomerAutoZoneSelfService/cazss-backend, pull requests merged in 2025-05, with the labels that each got.

#6 Bring Mvn Test Workflow Run to Main
  .github/workflows/rule_set.yaml
  src/test/java/com/autozone/cazss_backend/repository/AuthenticationStrategyAttributeRepositoryTest.java
  src/test/java/com/autozone/cazss_backend/repository/AuthenticationStrategyRepositoryTest.java
  src/test/java/com/autozone/cazss_backend/repository/CategoryRepositoryTest.java
  src/test/resources/application.properties
Labels: bug, github-actions, testing

#14 chore: merge SCRUM-166 into team-1-stable (SCRUM-166)
  .github/workflows/rule_set.yaml
Labels: github-actions, refactor

#30 feat: add getHistory functionality (SCRUM-18)
  src/main/java/com/autozone/cazss_backend/DTO/HistoryDTO.java
  src/main/java/com/autozone/cazss_backend/DTO/HistoryDetailedDTO.java
  src/main/java/com/autozone/cazss_backend/advice/GlobalExceptionHandler.java
  src/main/java/com/autozone/cazss_backend/controller/HistoryController.java
  src/main/java/com/autozone/cazss_backend/projections/HistoryProjection.java
  src/main/java/com/autozone/cazss_backend/repository/HistoryRepository.java
  src/main/java/com/autozone/cazss_backend/service/HistoryService.java
  src/test/java/com/autozone/cazss_backend/service/HistoryServiceTest.java
Labels: feature

#40 feat: Add function for creating endpoints (SCRUM-74)
  src/main/java/com/autozone/cazss_backend/DTO/CreateRequestVariableDTO.java
  src/main/java/com/autozone/cazss_backend/DTO/CreateResponseDTO.java
  src/main/java/com/autozone/cazss_backend/DTO/CreateResponsePatternDTO.java
  src/main/java/com/autozone/cazss_backend/DTO/CreateServiceDTO.java
  src/main/java/com/autozone/cazss_backend/controller/ServiceController.java
  src/main/java/com/autozone/cazss_backend/service/EndpointService.java
  src/main/java/com/autozone/cazss_backend/service/RequestBodyService.java
  src/main/java/com/autozone/cazss_backend/service/RequestVariableService.java
  src/main/java/com/autozone/cazss_backend/service/ResponseService.java
Labels: feature

#31 feature: create ResponsePatternController and add GET mapping for /response-patterns/{response_id} (SCRUM-65)
  src/main/java/com/autozone/cazss_backend/controller/ResponsePatternController.java
Labels: feature
